### ISSUE TITLE
Bottle release?

### ISSUE THREAD

**Issue by fauxpark** [osx-cross/homebrew-arm#20]
Could we please add bottles for `arm-gcc-bin`? Our Actions setup at https://github.com/qmk/homebrew-qmk does not seem to like that there's no bottles provided :)

During `brew test-bot --only-formulae` step:
```
Error: The following formulae cannot be installed from bottles and must be
built from source.
  mdloader and arm-gcc-bin@8
```

**Comment by ladislas** [comment]
I don't know if it's possible. We don't build anything we just untar the binaries provided by arm.

**Comment by fauxpark** [comment]
That just means we skip the compilation step. I tried `brew install --build-bottle arm-gcc-bin@8; brew bottle arm-gcc-bin@8` locally and it seems to have worked fine.

**Comment by ladislas** [comment]
If it's that easy, we can do that.

I don't have much time to work on it right now though. But I'll review a PR.

You'll need to implement (basically copy) the github actions workflow of osx-cross/avr

https://github.com/osx-cross/homebrew-avr/tree/master/.github/workflows

**Comment by ladislas** [comment]
The PR has been merged! Thanks a lot! 

Can you make a new PR to "bump" the formulae and run the workflow?

**Comment by fauxpark** [comment]
Thanks very much!

**Comment by ladislas** [comment]
Let me know if it works as you want :)

**Comment by fauxpark** [comment]
Yup, we got a nice green tick now 😄
https://github.com/qmk/homebrew-qmk/pull/21
