### ISSUE TITLE
arm-none-eabi for Apple Silicon

### ISSUE THREAD

**Issue by troian** [osx-cross/homebrew-arm#25]
fancy to homebrew `arm-none-eabi` native binaries for M1? i've got it built and tested

**Comment by ladislas** [comment]
we don't build anything, we actually just use pre-built packages from https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

As long as they don't provide a M1 binary, we won't be able to.
