### ISSUE TITLE
gcc 6 arm toolchains now on ARM web (not launchpad)

### ISSUE THREAD

**Issue by BrendanSimon** [osx-cross/homebrew-arm#4]
I note that the arm toolchains are now being maintained at ARM now.

https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

I has binaries for gcc-6 (6.2.1), as well as the gcc-5 series.

Could you update your hombrew-arm scripts to get the 6 series from ARM.  Possibly also the 5 series, but launchpad still has them so no harm leaving them as is :)

Thanks, Brendan.

**Comment by ladislas** [comment]
thanks for the info. we'll make the transition soon :)

**Comment by leojrfs** [comment]
tnks 👍 
I will update the toolchain ASAP.

As for having both 5 and 6 series, it will take a lot more work, so for now, I will just bump it to the latest stable.

**Comment by ladislas** [comment]
closed by #5
